services:
  claude-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: claude-sdk-server:latest
    container_name: claude-sdk-server
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    env_file:
      - .env
    restart: unless-stopped
