version: '3.8'

services:
  claude-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: claude-sdk-server:latest
    container_name: claude-sdk-server
    ports:
      - "${PORT:-8000}:8000"
    # Use .env file for environment variables
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claude-network

networks:
  claude-network:
    driver: bridge
